### ISSUE TITLE
Incorrect date conversion from Hebrew to Gregorian

### ISSUE THREAD

**Issue by tremendus** [AvrahamO/he-date#2]
Hi, 

When entering Peach 5779 - 15 Nissan 5779 as: 
```
new HeDate(5779, 8, 1)
```
... and logging to console, library correctly outputs the date, but the DAY of the week is wrong (Sunday): 
```
 Sun 15 Nisan 5779 00:00:00 GMT-0700 (Mountain Standard Time)
```
... and when converting to Gregorian with date.toISOString(), the lib incorrectly converts to: 
```
2019-04-21T07:00:00.000Z"
``` 

[Erev Pesach 5779 was Fri April 21](https://www.hebcal.com/holidays/pesach)

Unless I'm missing something, the Gregorian date is 2 days out. 

(Edited to point out day of week is wrong in Hebrew date string)

**Comment by AvrahamO** [comment]
Pesach 5779 was at April 20 as shown in [this calendar](https://www.hebcal.com/hebcal/?v=1&year=2019&month=4&s=on&maj=on&min=on&mod=on&mf=on&ss=on&nx=on&set=off&c=off).
In the list you mentioned they say it was at "Fri, 19 April 2019 **at sundown**", which means that the holiday actually begins on the night of 19-20. This is because according to the Jewish law, a day begins at the beginning of the night, not at midnight.

But, the library is converts it to April 21, which is a bug...
I fixed that, and published 1.2.2.

Thank you so much !
