### ISSUE TITLE
Conversion Problem with the Dates Before AD 1

### ISSUE THREAD

**Issue by ozdemirburak** [AvrahamO/he-date#3]
Greetings,

If the year value is less than AD 1, HeDate returns wrong values.  

For instance:

8 Shevat 3760 returns January 1, 1 while the correct value is [January 1, 0](https://www.hebcal.com/converter?hd=8&hm=Shvat&hy=3760&h2g=1). 

-------------------

This is how I did the conversion.

```js
const heDate = new HeDate(year, month, day);
const date = heDate.toLocaleDateString('en-US', options);
```

**Comment by ozdemirburak** [comment]
By the way, this is how I do the conversion.

```js
const heDate = new HeDate(year, month, day);
const date = heDate.toLocaleDateString('en-US', options);
```

I also found another discrepancies like 1 Adar 3763. This one returns October 13, 3 for me?

**Comment by AvrahamO** [comment]
The method `toLocaleDateString` interprets [Year Zero](https://en.wikipedia.org/wiki/Year_zero) to 1 BC, and returns the absolute year number. That's why you get `1/1/1` (instead of `1/1/-1`).

I suggest you to convert first to a native `Date` object, then use `getFullYear` which returns the correct number
```js
const heDate = new HeDate(3760, 4, 8);
const gregDate = new Date(heDate);

console.log(gregDate.getFullYear()); // -> 0
console.log(gregDate.getMonth()); // -> 0 (January)
console.log(gregDate.getDate()); // -> 1
```

**Comment by ozdemirburak** [comment]
You are right. Thanks for the explanation. Definitely the best library for the Hebrew calendar.
